version: '2' # 指定 Docker Compose 文件的版本

services:
  todolist: # 服务名称，可以自定义
    image: your-app-image:latest # 替换为您的镜像名称
    container_name: app-container # 容器名称
    build:
      context: ../ # Dockerfile 的路径，默认当前目录
      dockerfile: Dockerfile # Dockerfile 文件名
    ports:
      - "8000:80" # 将容器的 8080 端口映射到主机的 8080 端口
    environment:
      - ENV_VAR1=value1 # 定义环境变量
      - ENV_VAR2=value2
    volumes:
      - ./files:/app/files # 挂载主机目录到容器
    depends_on:
      - db # 依赖的服务名称

  db: # 数据库服务
    image: postgres:15 # 使用 PostgreSQL 的官方镜像
    container_name: db-container
    environment:
      POSTGRES_USER: user # 数据库用户名
      POSTGRES_PASSWORD: password # 数据库密码
      POSTGRES_DB: app_db # 数据库名称
    volumes:
      - db_data:/var/lib/postgresql/data # 数据持久化

  # redis: # 可选的 Redis 服务
  #   image: redis:7
  #   container_name: redis-container
  #   ports:
  #     - "6379:6379"

volumes:
  db_data: # 定义一个持久化卷
